version: "3.8"

services:
  app:
    build: .
    env_file: ".env"
    tty: true
    stdin_open: true
    command: [
      "uvicorn", "api:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--workers", "1",
      "--log-level", "debug",
      "--reload"]
    volumes:
      - "./app:/app"
    ports:
    - "8000:8000"
