version: "3.8"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: [
      "uvicorn", "main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--workers", "1",
      "--reload"]
    volumes:
      - "./app:/app"
    ports:
    - "8000:8000"
